-- Generated by scripts/migrate-content.mjs. Replaces all projects and timeline entries.
DELETE FROM project_media;
DELETE FROM projects;
DELETE FROM timeline;
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('pitchforks', 'Pitchforks & Paragraphs', 'A fast-paced medieval typing game where you cast word-spells to quell peasant riots. Built from scratch in Unity.', '<p>Pitchforks & Paragraphs is a wave-based typing game where players must type words displayed on peasants'' signs to cast spells and disperse them. The game features a dynamic difficulty system, a combo-based scoring mechanism that rewards speed and accuracy, and online leaderboards.</p>', 'gamepad-2', '["Unity","C#","Blender","MagicaVoxel"]', '[{"label":"Platform","value":"Web"},{"label":"Type","value":"Game"}]', '[{"label":"Play on itch.io","url":"https://dustylv.itch.io/pitchforksnparagraphs"}]', 1, 'published', 0);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m1', 'pitchforks', 'upload', 'projects/pitchforks/1.png', 0);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m2', 'pitchforks', 'upload', 'projects/pitchforks/2.png', 1);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m3', 'pitchforks', 'upload', 'projects/pitchforks/3.png', 2);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m4', 'pitchforks', 'upload', 'projects/pitchforks/4.png', 3);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('lipke-guide', 'Žanis Lipke Memorial Digital Guide', 'A digital guide to enhance the memorial experience.', '<p>Creation of digital guide to run on an Android tablet. It provides additional information to the physical exhibits inside the memorial - like a real-life guide would.
        <br><br>
        It gives insights for each exhibit with images, text and videos. To improve the user experience, Bluetooth beacons we''re added to automatically switch to the nearest exhibit and show its content.<br>
        To improve this applications longevity, a custom content management system (CMS) was created that the memorial employees or curators can edit and add new content.
        <br><br>
        An outdoors mode was created to give visitors a guided tour - a custom route was created that takes them around the memorial area to see various points of interest. In these points, contextual information is given, as well as some Augmented Reality (AR) elements
        are added to some points.
        Visitors are guided with a top-down map of the area, like any other navigation, with the POIs marked on the map.
        <br><br>
        Since these Android tablets would not have internet connection outside, the navigation was made from the ground-up. An offline map tiling system and a navigation line drawing system were created.
        </p>', 'landmark', '["Unity","C#","AR","Android","Google Services"]', '[{"label":"Platform","value":"Mobile (Android)"},{"label":"Type","value":"EdTech"}]', '[{"label":"Lipke memorial","url":"https://lipke.lv/en/"}]', 0, 'published', 1);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('rix', 'RIX Airport Digital Twin 3D Model', 'Creation of Riga (RIX) airport 3D model.', '<p>Creation of 3D model for RIX airport runways and surrounding territory. Modeled and textured the terrain, signage and other necessary objects, as well as buildings.
        <br><br>
        The model needed to be as performant as possible, so custom shaders were created for terrain texturing, to use Vertex Colors for masking. As well as, creation and use of texture atlases for signage, ground lines, etc.
        </p>', 'plane', '["Blender","Unity","Amplify Shader"]', '[{"label":"Platform","value":"VR Standalone"},{"label":"Type","value":"3D Model"}]', '[]', 0, 'published', 2);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('lipke-vr', 'Žanis Lipke Memorial VR Experience', 'A VR experience for the Žanis Lipke Memorial museum, allowing virtual exploration of the hideout used to save Jews in WWII.', '<p>This VR application virtually recreates the woodsman''s hut and the underground bunker where Žanis Lipke hid people during WWII. The experience allows users to explore the historical site and is used in the museum for educational purposes.</p>', 'landmark', '["Unity","C#","VR","Blender"]', '[{"label":"Platform","value":"VR Standalone"},{"label":"Type","value":"Museum Exhibit"}]', '[{"label":"Lipke memorial","url":"https://lipke.lv/en/"}]', 0, 'published', 3);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m5', 'lipke-vr', 'upload', 'projects/lipkevr/LipkesBunkurs.png', 0);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m6', 'lipke-vr', 'upload', 'projects/lipkevr/Lipke_Game1.png', 1);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m7', 'lipke-vr', 'upload', 'projects/lipkevr/Lipke_Game2.png', 2);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m8', 'lipke-vr', 'upload', 'projects/lipkevr/Lipke_Game3.png', 3);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m9', 'lipke-vr', 'upload', 'projects/lipkevr/Lipke_props1.png', 4);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m10', 'lipke-vr', 'upload', 'projects/lipkevr/Lipke_props2.png', 5);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('volga-heatwave', 'Volga Heatwave', 'A hobby game about a dog trapped in a hot car who must attract attention to be saved before the temperature gets too high.', '<p>Volga Heatwave is a game about a dog trapped in a hot car who must attract the attention of passersby to be saved. The player''s goal is to fill an "attention meter" by interacting with objects in the car, which makes a crowd gather outside. All the while, a temperature meter is constantly rising, and if it reaches its maximum value, the game is over. 
        <br><br>
        This was a solo project where I handled all development and art aspects.
        This was made for the Unity development course while attending masters studies in Vidzeme University.
        Afterwards, I polished the game and submitted it to the Latvian Gamedev association organized game jam/competition ''BRSD 12'' (Beidz runāt, sāc darīt | Stop talking, start doing). Came in 7th out of 15 submissions.
        </p>', 'dog', '["Unity","Blender"]', '[{"label":"Platform","value":"PC"},{"label":"Type","value":"Game"}]', '[{"label":"Play on itch.io","url":"https://dustylv.itch.io/volga-heatwave"}]', 0, 'published', 4);
INSERT INTO project_media (id, project_id, kind, url, position) VALUES ('m11', 'volga-heatwave', 'video', 'https://www.youtube.com/watch?v=VvSTKLORBHg', 0);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m12', 'volga-heatwave', 'upload', 'projects/volga/1.png', 1);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m13', 'volga-heatwave', 'upload', 'projects/volga/2.png', 2);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m14', 'volga-heatwave', 'upload', 'projects/volga/3.png', 3);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('crayfish-rush', 'Crayfish Rush', 'A VR experience where the player has to catch crayfish in a river.', '<p>This is a VR game for Ape museum in Latvia. The games purpose is to allow players to immerse themselves in an activity that''s becoming quite rare - catching crayfish in a river. </p><br>
      <p>The player must catch as many crayfish as possible in the given time. They are presented with 3 crayfish traps in the river next to them and they must wait for the crayfish to go into them. When that happens, the player pulls up the trap and takes the crayfish and places it into the bag that''s around their neck. <br>
      This process is repeated until the end of the game. The amount of crayfish in the bag is counted at the end of the game and shown on the scoreboard. Players can compete for the highest score.</p>', 'crab', '["Unity","C#"]', '[{"label":"Platform","value":"VR Standalone"},{"label":"Type","value":"Edutainment"}]', '[]', 0, 'published', 5);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m15', 'crayfish-rush', 'upload', 'projects/crayfish/Game1.jpg', 0);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m16', 'crayfish-rush', 'upload', 'projects/crayfish/Game2.jpg', 1);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m17', 'crayfish-rush', 'upload', 'projects/crayfish/Game3.jpg', 2);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m18', 'crayfish-rush', 'upload', 'projects/crayfish/Game4.jpg', 3);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('izlidzi-vitolam', 'Izlīdzi vītolam', 'A Virtual Reality choir conducting game with gesture recognition.', '<p>A Virtual Reality choir conducting game with gesture recognition. <br><br> The game serves as an interactive experience to see what a choir conductor does. The player has to perform various patterns with arm movements that correspond with what an actual conductor would make to give instructions to the choir.</p>', 'heart-handshake', '["Unity","C#"]', '[{"label":"Platform","value":"PC VR"},{"label":"Type","value":"Edutainment"}]', '[]', 0, 'published', 6);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m19', 'izlidzi-vitolam', 'upload', 'projects/vitols/VitolsLogo.jpg', 0);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m20', 'izlidzi-vitolam', 'upload', 'projects/vitols/game1.png', 1);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m21', 'izlidzi-vitolam', 'upload', 'projects/vitols/game2.png', 2);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('zaao', 'ZAAO VR Sorting Game', 'A VR game for a waste management company (ZAAO) to educate players on proper waste sorting in an interactive way.', '<p>This educational VR game gamifies the process of waste sorting. Players are placed in a virtual environment where they must correctly sort different types of trash into the appropriate bins under a time limit.</p><br>
      <p>The main challenge was the use of a 360° image for the background and 3D models for the interactable objects. This choice was made so that the game looks realistic. Creating the environment as a 3D model was not feasible as the game was supposed to run on an Oculus Go headset, and does not have the horsepower to process that much.</p>', 'recycle', '["Unity","C#","VR","Blender"]', '[{"label":"Platform","value":"Standalone VR"},{"label":"Type","value":"Edutainment"}]', '[]', 0, 'published', 7);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m22', 'zaao', 'upload', 'projects/zaao/GameLogo.png', 0);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m23', 'zaao', 'upload', 'projects/zaao/MainMenu.png', 1);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m24', 'zaao', 'upload', 'projects/zaao/Game1.png', 2);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m25', 'zaao', 'upload', 'projects/zaao/Game2.png', 3);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('train-dispatch', 'Train Dispatcher Game', 'A train dispatch edutainment game for Gulbene train museum. ', '<p>Allows the player to take on the role of a train dispatch and make decisions to divert trains to the correct rails. Gives an insight on what a train dispatch actually does. <br><br>
The player is given a description of the situation and they must choose an appropriate course of action from the given choices. </p>', 'train', '["Unity","C#"]', '[{"label":"Platform","value":"PC"},{"label":"Type","value":"Edutainment"}]', '[]', 0, 'published', 8);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m26', 'train-dispatch', 'upload', 'projects/train/TrainDispatchLogo.png', 0);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m27', 'train-dispatch', 'upload', 'projects/train/Game1.png', 1);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m28', 'train-dispatch', 'upload', 'projects/train/Game2.png', 2);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m29', 'train-dispatch', 'upload', 'projects/train/Game3.png', 3);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('art-plus', 'Art+', 'Various 3D models for ART+ AR application viewable in multiple places across Latvia', '<p>ART+ is a collaborative artist effort of bringing art experiences to AR. In different places in Liepaja, Kuldiga and Valmiera, people can use their phones or tablets to view and experience various art and other significant objects.
<br><br>
You can check it out here: https://artplus.app/
<br><br>
My part in this was to create a few 3D models and add some effects to some of them:
<br>
    <ul>
    <li> - Airplane "KOD" or "Ventas Eagle"</li>
    <li> - Roots</li>
    <li> - The white clover</li>
    <li> - Libau - Romny Railway</li>
    </ul>
</p>', 'image-plus', '["Blender","AR","Unity"]', '[{"label":"Platform","value":"Augmented Reality"},{"label":"Type","value":"3D Model"}]', '[]', 0, 'published', 9);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m30', 'art-plus', 'upload', 'projects/artplus/artplus_clover.jpg', 0);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m31', 'art-plus', 'upload', 'projects/artplus/artplus_roots.jpg', 1);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m32', 'art-plus', 'upload', 'projects/artplus/artplus_taube-plane.jpg', 2);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m33', 'art-plus', 'upload', 'projects/artplus/artplus_train.png', 3);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('audio-viz', 'Audio Visualizations', 'Hobby audio vizualization renders.', '<p>These are some personal hobby projects where I wanted to create an animation with audio, where objects in the scene would react to audio. Both projects are for already songs, not original tracks.
      <br>
      </p>', 'bar-chart-3', '["Blender"]', '[{"label":"Platform","value":"Video"},{"label":"Type","value":"3D Model"}]', '[]', 0, 'published', 10);
INSERT INTO project_media (id, project_id, kind, url, position) VALUES ('m34', 'audio-viz', 'video', 'https://www.youtube.com/watch?v=DRLJPnU8gjk', 0);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('bog-sim', 'Bog Simulator', 'An automated generation of digital twin in virtual reality for interaction with specific nature ecosystem.', '<p>This scientific project was aimed towards creating a VR experience to visualize realtime simulation data in an easier form. The simulation was made for a bog ecosystem and as the main parameter to be simulated was underground water level. <br><br>
      This water level is impacted by various factors, but one of the goals for this visualization was how human actions impact the ecosystem. And to demonstrate it, tree cutting was chosen as the main action. If the user cuts down a tree, the simulation is run and the water level data is updated.
<br><br>
This project incorporates GIS data to create the virtual terrain and various drone LIDAR datasets used to place vegetation.</p>', 'leaf', '["Unity","VR","Blender"]', '[{"label":"Platform","value":"PC VR"},{"label":"Type","value":"Simulation"}]', '[]', 0, 'published', 11);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('motor-assembly', 'Motor Assembly VR', 'A VR learning environment for teaching the step-by-step process of assembling a complex electric motor.', '<p>This technical training application guides users through the intricate process of motor assembly. It features interactive parts, instructional overlays, and performance feedback to ensure effective learning.
      <br><br>
      The applications purpose is to allow university students to learn mechatronics in a virtual environment. 
Main idea is to allow to learn how to assemble and operate various mechanical devices.
<br><br>
This training application has less focus on safety, but more on the different levels of depth a training environment can have. 
<br>
In this project, also a grading system was implemented that allows to gain more insights on how well does the student understands the subject and where they might need to improve.
<br><br>
As an example, an electric motor was chosen. The application has three levels of complexity.</p>', 'cog', '["Unity","VR","C#","Blender"]', '[{"label":"Platform","value":"Standalone VR"},{"label":"Type","value":"Training"}]', '[]', 0, 'published', 12);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m35', 'motor-assembly', 'upload', 'projects/nextgen/Showcase1.png', 0);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m36', 'motor-assembly', 'upload', 'projects/nextgen/Showcase2.png', 1);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m37', 'motor-assembly', 'upload', 'projects/nextgen/Showcase3.png', 2);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m38', 'motor-assembly', 'upload', 'projects/nextgen/Motor.png', 3);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m39', 'motor-assembly', 'upload', 'projects/nextgen/IntTut1.png', 4);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m40', 'motor-assembly', 'upload', 'projects/nextgen/IntTut2.png', 5);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('safescaff', 'SafeScaff VR', 'A VR safety training simulation for construction workers, focusing on the correct and safe procedures for erecting scaffolding.', '<p>SafeScaff provides a hands-on, risk-free environment for workers to learn and be tested on scaffolding safety protocols, helping to reduce workplace accidents.
      <br><br>
      The users have the task of building a scaffolding structure while performing all safety measures. This includes wearing all the necessary safety equipment, constructing the scaffolding in the correct order, securing all scaffolding pieces so that they don''t move.
<br><br>
The whole process and the users actions are recorded. They are used afterwards to determine if the user did everything correctly or what mistakes were made. That allows for a deeper learning process that helps users to learn faster and safer.
<br><br>
This project supports both singleplayer and multiplayer modes.</p>', 'construction', '["Unity","VR","C#","Blender"]', '[{"label":"Platform","value":"Standalone VR"},{"label":"Type","value":"Training"}]', '[]', 0, 'published', 13);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('exonicus', 'XR Prototype for Exonicus Inc.', 'Freelance job for Exonicus Inc. to create a prototype for ArUco marker tracking.', '<p>The main idea of the prototype was to test how well the Vive XR Elite headset performs with tracking ArUco markers and if it would be suitable to use.
<br><br>
By using the headset passthrough and ability to detect and track markers in real-time, digital objects would be attached to each marker and follow it.
<br><br>
This was done in Unity, using the Vive Wave SDK packages, which provide ArUco marker tracking support. At the time of development the tracking performance was awful and not suitable for smooth real-time operation.
<br><br>
This was a solo project where I developed and implemented all of the logic based on the provided specifications.</p>', 'activity', '["Unity","XR","C#"]', '[{"label":"Platform","value":"Standalone VR"},{"label":"Type","value":"Prototyping"}]', '[]', 0, 'published', 14);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('overly', 'Exposition app for OverlyApp', 'Freelance job for OverlyApp to create an exposition application.', '<p>An exposition app for Ventspils science centre. The app allows users to view online webcams showing wild animals such as eagle or stork nests. The app also has a wide library of animals, birds and sea creatures found in Latvia.
<br><br>
The app was made in Unity with its UI components to display necessary information.
<br><br>
It is a static app where the exposition information is mostly static - for this reason a simple Excel spreadsheet was used as a database for animal descriptions and other info. This information is loaded and shown in the game UI as necessary.
<br><br>
Another part was the webcam viewer for which it was necessary to display streams from Youtube and other sources. For this, VLC plugin was integrated.</p>', 'layers', '["Unity","VLC Player"]', '[{"label":"Platform","value":"PC"},{"label":"Type","value":"Museum Exhibit"}]', '[]', 0, 'published', 15);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m41', 'overly', 'upload', 'projects/animalexpo/AnimalExposition1.png', 0);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m42', 'overly', 'upload', 'projects/animalexpo/AnimalExposition2.png', 1);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m43', 'overly', 'upload', 'projects/animalexpo/AnimalExposition3.png', 2);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('find-yourself', 'Find Yourself in Europe', 'A digital board game for kids about Valmiera city, Europe and various professions.', '<p>A digital version of an already existing non-digital educational board game, made for Valmiera city library.
<br><br>
This is an educational board game with questions about Valmiera city, Europe and 10 different professions. The purpose is to educate children in a more engaging and interactive way.
<br><br>
The main goal of the game is to collect points by correctly answering to questions. The winner is who has the most points.</p>', 'map', '["Unity","C#","SQLite"]', '[{"label":"Platform","value":"PC"},{"label":"Type","value":"Educational Game"}]', '[]', 0, 'published', 16);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m44', 'find-yourself', 'upload', 'projects/atrodisevieiropa/ASE_1.jpg', 0);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m45', 'find-yourself', 'upload', 'projects/atrodisevieiropa/ASE_2.jpg', 1);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m46', 'find-yourself', 'upload', 'projects/atrodisevieiropa/ASE_3.jpg', 2);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m47', 'find-yourself', 'upload', 'projects/atrodisevieiropa/ASE_4.jpg', 3);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m48', 'find-yourself', 'upload', 'projects/atrodisevieiropa/ASE_5.jpg', 4);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('stellar-miner', 'Revenge of the Stellar Miner', 'A 2D mobile game where players navigate a spaceship through asteroid fields to collect resources while avoiding enemies.', '<p>
This is a top-down space shooter where you gather resources, upgrade your space ship and fight the boss.
<br><br>
You must destroy asteroids with your ships weapons. You can upgrade and buy new ones to help you speed up the gathering process. There''s quite a few upgrades so it might take a while to upgrade fully.
<br><br>
You can do missions, that award you resources or gold. The missions are "destroy x amount" or "collect x amount".
<br><br>
The stronger you get, the higher the chance to get noticed by SpaceCorp, and they might send some AI ships to pester you.
<br><br>
The game has rebindable keys within settings. It also has a save function.
<br><br>
The game UI has toggleable information tooltips, they explain the various UI elements and screens.</p>', 'rocket', '["Unity","C#","Blender"]', '[{"label":"Platform","value":"PC"},{"label":"Type","value":"Game"}]', '[]', 0, 'published', 17);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m49', 'stellar-miner', 'upload', 'projects/projectspace/1.png', 0);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m50', 'stellar-miner', 'upload', 'projects/projectspace/2.png', 1);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m51', 'stellar-miner', 'upload', 'projects/projectspace/3.png', 2);
INSERT INTO project_media (id, project_id, kind, r2_key, position) VALUES ('m52', 'stellar-miner', 'upload', 'projects/projectspace/4.png', 3);
INSERT INTO projects (id, title, description, long_description, icon, tags, details, links, is_featured, status, position) VALUES ('spatial', 'Spatial.io Custom Environments and Logic', 'A research project on Spatial.io and its capabilities.', '<p>This was a project within Vidzeme University of Applied Sciences for using VR technologies for immersive environments. In this case, main focus was on theatre and how Spatial can be used to help actors train for their plays remotely. Second focus was on how to use Spatial for group activities such as team-building work events.
<br><br>
Custom environments and logic was created using Spatial Creator Toolkit SDK for Unity.
<br><br>
Much of the project was exploring the SDK, creating various 3D environments, adding built-in Spatial functionalities, and also creating new logic with Visual Scripting specific for Spatial.</p>', 'users', '["Unity","VR","C#","Spatial.io SDK"]', '[{"label":"Platform","value":"VR & Flatscreen"},{"label":"Type","value":"Prototyping"}]', '[]', 0, 'published', 18);
INSERT INTO timeline (id, section, title, organization, period, description, resume_bullets, status, position) VALUES ('t1', 'experience', '3D Artist', 'Exonicus R&D', '2025 - Present', 'Creating 3D content for medical training and other applications, for military context.', '[]', 'published', 0);
INSERT INTO timeline (id, section, title, organization, period, description, resume_bullets, status, position) VALUES ('t2', 'experience', 'Unity Developer', 'Vidzeme University of Applied Sciences | VRAR Laboratory', '2019 - Present', 'Developer for interactive VR training and educational modules, simulations and other experiences. Responsible for architecture, logic implementation, graphical elements and performance optimization.', '["Developer for interactive VR training and educational modules, simulations and other experiences.","Responsible for architecture, logic implementation, graphical elements and performance optimization."]', 'published', 1);
INSERT INTO timeline (id, section, title, organization, period, description, resume_bullets, status, position) VALUES ('t3', 'experience', 'Lecturer', 'Vidzeme University of Applied Sciences', '2019 - Present', 'Giving lectures on 3D modeling. Using Blender as the main tool. Giving a good starting point for students to start creating 3D models for games.', '["Giving lectures on 3D modeling.","Giving a good starting point for students to start creating 3D models for games.","Using Blender as the main tool."]', 'published', 2);
INSERT INTO timeline (id, section, title, organization, period, description, resume_bullets, status, position) VALUES ('t4', 'experience', 'Freelance Developer', NULL, '2018 - Present', 'Developer for interactive VR and flatscreen experiences in Unity. Responsible for architecture, logic implementation, graphical elements and performance optimization.', '["Developer for interactive VR and flatscreen experiences in Unity.","Responsible for architecture, logic implementation, graphical elements and performance optimization."]', 'published', 3);
INSERT INTO timeline (id, section, title, organization, period, description, resume_bullets, status, position) VALUES ('t5', 'education', 'Mg.sc.comp. in Sociotechnic Systems Modeling', 'Vidzeme University of Applied Sciences', '2016 - 2018', 'Specialized in sociotechnic model output data visualization. Graduated with honors after completing a thesis on an interactive simulation data visualization tool for virtual reality made in Unity.', '[]', 'published', 0);
INSERT INTO timeline (id, section, title, organization, period, description, resume_bullets, status, position) VALUES ('t6', 'education', 'B.Sc. in Computer Science', 'Vidzeme University of Applied Sciences', '2012 - 2016', 'General computer science education with an interest in game development and computer graphics. Graduated with honors after completing a thesis on creating a digital board game in Unity.', '[]', 'published', 1);
